# Generated by Django 4.2.5 on 2023-10-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='statusys',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Видимость поста'),
        ),
    ]
