# Generated by Django 4.2.6 on 2024-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Картинка'),
        ),
    ]
