# Generated by Django 4.2.6 on 2024-02-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_commentary_alter_actor_options_alter_agerate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеров', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='agerate',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['-time_created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страну', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссеров', 'verbose_name_plural': 'Режиссеры'},
        ),
        migrations.AddField(
            model_name='kino',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка фильма'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='ager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.agerate', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director', verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.status', verbose_name='Подписка'),
        ),
    ]
