# Generated by Django 4.2.6 on 2024-03-04 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0013_remove_commentary_like_alter_commentary_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='meep_like', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
