# Generated by Django 4.2.6 on 2024-03-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_commentary_disliked_commentary_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
