# Generated by Django 4.2.6 on 2024-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_visitscounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitscounter',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Счетчик посещений'),
        ),
        migrations.AlterField(
            model_name='visitscounter',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс сайта'),
        ),
    ]
